### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by XrTV** [MatthewBooth/OTAUpdates#15]
Hey, it's better, but not quite...
When you update the firmware in TWRP popping up:
E: Failed to sysMapFile '/sdcard/OTAUpdate**scm**-12.1-20150527-UNOFFICIAL-[NG]-eng-e975.zip'
E: Error installing zip file '/sdcard/OTAUpdate**scm**-12.1-20150527-UNOFFICIAL-[NG]-eng-e975.zip'

And here is how it should be:
/sdcard/OTAUpdates**/**cm-12.1-20150527-UNOFFICIAL-[NG]-eng-e975.zip

**Comment by MatthewBooth** [comment]
Is this in Open Recovery Script generation?

**Comment by XrTV** [comment]
Yes

**Comment by MatthewBooth** [comment]
Just pushed a fix to master and aosp :)

**Comment by XrTV** [comment]
Thanks! =)

**Comment by XrTV** [comment]
Have an idea, what if you add the Addons button to open a file, folder, to install?

**Comment by MatthewBooth** [comment]
For the new "InstallAfterFlash" folder implementation? I'm still working that out which is why I didn't add it now.

**Comment by XrTV** [comment]
Understand)
I will wait impatiently for the release)

**Comment by MatthewBooth** [comment]
Don't worry, the way it is now isn't ideal, I know this. I will figure out the best way of doing it. I also want a way of flashing the file immediately on download (or a button to flash it) and a way of queuing up some files to flash as well.

**Comment by MatthewBooth** [comment]
I will close this as an issue now, though :+1:
