### ISSUE TITLE
Wrong download directory

### ISSUE THREAD

**Issue by proDOOMman** [MatthewBooth/OTAUpdates#17]
All files are downloaded to the directory /storage/sdcard0/storage/sdcard0/OTAUpdates/

**Comment by pixelase** [comment]
I confirm too

**Comment by MatthewBooth** [comment]
Should be fixed in 2.4.5 now guys. 

MatthewBooth/OTAUpdates@b154d00a09a26d8c93495354cafaecb1c98b47df
