### ISSUE TITLE
Spacing Issue

### ISSUE THREAD

**Issue by Gunthermic** [MatthewBooth/OTAUpdates#18]
In the OTA.xml

<VersionName> SampleRom v1.1 </VersionName>

In app it trims out the space and displays SampleRomv1.1 in Main screen and Download screen.

**Comment by Gunthermic** [comment]
Add Catagories to Addon section of app.

we could then have for example under Addons:

Themes
Themes Apps
Mods
Stock (Revert Mods)

This would expand just the way it looks is all.  Make it collapeable, but the main screen just show whats new as always..

**Comment by MatthewBooth** [comment]
This should be it: 327cb487fd8a4cc247a82af98f6c97c8102c6c6b

**Comment by Gunthermic** [comment]
Fixed, thank you!!!
