### ISSUE TITLE
Addon Categories

### ISSUE THREAD

**Issue by Gunthermic** [MatthewBooth/OTAUpdates#19]
Add Categories to Addon section of app.

we could then have for example under Addons:

Themes
 Themes Apps
 Mods
 Stock (Revert Mods)

This would expand just the way it looks is all. Make it collapeable, but the main screen just show whats new as always..

I would think just another metatag in the OTA.xml and of course code to read it.

**Comment by XrTV** [comment]
1. Have a look at romhut.
2. Write to the administrator a proposal to add categories.
3. Stop trying to scribble the text. So, as the author can do. It is all done on the administrator side of the site romhut. Even if the author of this application will add this functionality, it just will not work.

**Comment by Gunthermic** [comment]
Thank you for your comments. Author asked me to put these there. It's already being worked on FYI.

**Comment by scottrobertson** [comment]
@Gunthermic this has been added to romhut.

@Mr-MEX It's actually a bit of both. We (romhut) have to add support for it, but there is still work for @MatthewBooth to do in the app.

**Comment by scottrobertson** [comment]
We have the following categories. Can you think of anymore?
- Default
- Apps
- Stock Apps
- Themes
- Kernels
- Google Apps
- Mods

**Comment by Gunthermic** [comment]
Rom Patches? we have Full rom's, how about Rom Patches, that may add multi
fucntiosnto a rom, but dont require full rom vs a Mod..

Just a different way to approach it is all. Otherwise I think these others
hit the mark

**Comment by scottrobertson** [comment]
Multiple file uploads per version will be coming soon :) So you can have a full upload and a patch upload of the same rom version.

**Comment by MatthewBooth** [comment]
Hopefully you won't be able to upload a patch without a full version, though

**Comment by MatthewBooth** [comment]
This is now added in the v3 rewrite and won't be getting removed, so I can close this as completed
