### ISSUE TITLE
Update Time

### ISSUE THREAD

**Issue by Gunthermic** [MatthewBooth/OTAUpdates#21]
us to define default time(build.prop) to check for updates.

New rom, but want to ensure it check for new updates right after flashing...

**Comment by XrTV** [comment]
Anything automatic is not updated and will not be updated, it already the care of the builder and not the author of this program.

**Comment by MatthewBooth** [comment]
@Mr-MEX, It's ok, this what the issues page is for. We're using it to log feature requests.

@Gunthermic, the app checks for updates on every boot :)
