### ISSUE TITLE
Switch to using /rom/{slug}/versions for romhut roms

### ISSUE THREAD

**Issue by scottrobertson** [MatthewBooth/OTAUpdates#22]
Switching to using `/rom/{slug}/versions` will allow the app to show a history of versions, and also allow us to expand on this further in the future. It should also make the onboarding process for devs much easier.

Append `?redirect=true` to the current OTA urls when you release the app, and it will redirect them to use the new versions.xml/json. This will mean that both versions will work until all devs move over.

**Comment by MatthewBooth** [comment]
Yep, for now I will keep it as it is (and redirect, just grab latest version) until I figure out the best way of presenting the previous versions.

**Comment by scottrobertson** [comment]
Awesome :)

**Comment by MatthewBooth** [comment]
Switched to using /rom/{slug}.json now, which is better than this.
