### ISSUE TITLE
ota stop running

### ISSUE THREAD

**Issue by ghost** [MatthewBooth/OTAUpdates#29]
Download ota package after exiting the program download interface, when the package download is complete, ota stop running

: Shutting down VM
: FATAL EXCEPTION: main
: Process: com.ota.updates, PID: 30682
: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@1a5690e6 is not valid; is your activity running?
:   at android.view.ViewRootImpl.setView(ViewRootImpl.java)
:   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java)
:   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java)
:   at android.app.Dialog.show(Dialog.java)
:   at com.ota.updates.tasks.LoadUpdateManifest.onPreExecute(LoadUpdateManifest.java)
:   at android.os.AsyncTask.executeOnExecutor(AsyncTask.java)
:   at android.os.AsyncTask.execute(AsyncTask.java)
:   at com.ota.updates.activities.MainActivity$CompatibilityTask.onPostExecute(MainActivity.java)
:   at com.ota.updates.activities.MainActivity$CompatibilityTask.onPostExecute(MainActivity.java)
:   at android.os.AsyncTask.finish(AsyncTask.java)
:   at android.os.AsyncTask.access$600(AsyncTask.java)
:   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
:   at android.os.Handler.dispatchMessage(Handler.java)
:   at android.os.Looper.loop(Looper.java)
:   at android.app.ActivityThread.main(ActivityThread.java)
:   at java.lang.reflect.Method.invoke(Native Method)
:   at java.lang.reflect.Method.invoke(Method.java:372)
:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
: isApplicationStateBlocked userId 0 pkgname com.ota.updates

**Comment by MatthewBooth** [comment]
Thanks for these. I'm planning a large rewrite over the next few weeks, which should address most of these concerns.

**Comment by ghost** [comment]
Can you help me fix this problem? I simply can fix this problem, I can not wait that long.

**Comment by scottrobertson** [comment]
@sun2009 feel free to submit a PR if you can fix it. @MatthewBooth is super busy with Uni stuff at the moment though.

**Comment by MatthewBooth** [comment]
I'm marking this as wontfix because it would require too much rewriting code, when I'm in the middle of a ground-up rewrite.
