### ISSUE TITLE
MD5 checking improvements

### ISSUE THREAD

**Issue by MarcusJT** [MatthewBooth/OTAUpdates#30]
- App should perform an MD5 check automatically after downloading (with opt out in settings)
- Clearer indication of MD5 failure needed, and it should also offer to delete+redownload+recheck

**Comment by LordMrcS** [comment]
And to me MD5 test is always failing.. Don't know why. (Dowloading JFLTE-GPE-20150702)

**Comment by MarcusJT** [comment]
I've been having the same problem with the same ROM, but it didn't occur to
me that the problem might be with the MD5 checker itself. Will download
manually, use another MD5 checker, and report back.

**Comment by MarcusJT** [comment]
Yes, the MD5 checks out fine so the issue must be with the MD5 checker in
OTAUpdates itself.

**Comment by LordMrcS** [comment]
Found a strange thing with the OTAUpdates downloads folder, it saves the files under /data/media/0/OTAUpdates and for some reason the contents there didn't show up at /sdcard/OTAUpdates/ and /storage/sdcard0/OTAUpdates/. Once I moved the file within it worked fine!

**Comment by LordMrcS** [comment]
I must add that I was losing 2.6gb of .zip downloads in that folder. Since the APP was unable to locate the file once the download had finished. That was the reason I started looking for it.

**Comment by MarcusJT** [comment]
So you think the issue is that the app is not checking for the file in the same location that is specified in its Settings and is lacking an error message to indicate this?

**Comment by LordMrcS** [comment]
Yes, I believe that's pretty much it.

**Comment by MatthewBooth** [comment]
At the moment, guys, I'm here: https://github.com/MatthewBooth/OTAUpdates/tree/v3_rewrite trying to rewrite this whenever I get chance, which is on my lunch breaks and weekends :)

**Comment by MatthewBooth** [comment]
Just a note that the suggestions in the opening comments should definitely be features.

**Comment by MarcusJT** [comment]
Glad you agree!
