### ISSUE TITLE
Uninstall in unsupported ROM message

### ISSUE THREAD

**Issue by MarcusJT** [MatthewBooth/OTAUpdates#32]
I suggest that your message for unsupported ROMs should include an "Uninstall" button at the bottom so that users remove the app straight away, thereby avoiding the possibility that they open it again / another day and get frustrated. This should help reduce the number of 1\* reviews received.

PS - I've also downvoted the stupid reviews I've seen.

**Comment by MatthewBooth** [comment]
Thanks for this. I will definitely consider adding this during my rewrite, if it is possible to uninstall the app itself.

I think a lot of the 1\* reviews are either part of the language barrier (which I could use translators for) or just sheer stupidity of the user for not reading the description. :/

**Comment by MarcusJT** [comment]
```
Intent intent = new Intent(Intent.ACTION_DELETE);
intent.setData(Uri.parse("package:com.android.calculator2"));
startActivity(intent);
```

from http://stackoverflow.com/questions/6813322/install-uninstall-apks-programmatically-packagemanager-vs-intents
