### ISSUE TITLE
storage path is messed up

### ISSUE THREAD

**Issue by saintxseiya** [MatthewBooth/OTAUpdates#33]
Hi,

since the last update and the modification on the storage code parts, on my devices the OTAupdates are not longer stored under "/storage/emulated/0/OTAupdates" but now under "/storage/emulated/0/storage/emulated/0/OTAupdates" 

In twrp it is:
/sdcard/storage/emulated/0/OTAupdates

That means, the recovery script does not work and i have to flash it manually again. :(

Cheers,

Saint

**Comment by MatthewBooth** [comment]
I've had a lot of back and forth with this. It's seems to be that Android is handling the Environment variables for internal storage differently based on the device. :/

Not sure there is much I can do about it but I'm going to try and look at v2 tonight and publish a patched version for a few issues and I will make sure this is looked at.

**Comment by saintxseiya** [comment]
Hi Mat,

at least you are having a look at it, until then, i am staying with one of your old releases, as those are still working like a charm, without issues.

Thanks for fixing!

Saint!

**Comment by MatthewBooth** [comment]
I have to say this issue is so, so confusing :( On my devices, and my Emulator, the path returns as  /storage/emulated/0/ for MD5, Addons and downloads :/

**Comment by saintxseiya** [comment]
Hehe it would be boring, if there wasn't anymore to wonder about in the IT world right? :+1:
