### ISSUE TITLE
Problem install other zip files

### ISSUE THREAD

**Issue by GounalakisOrestis** [MatthewBooth/OTAUpdates#34]
After flash the rom update the app try to install the zip files  in the installafterflash folder but there is a problem with the path a "/" is missing  between  the sdcard  and OTAUpdates version 2.5.1 2.5.2

-- Installing: /sdcardOTAUpdates/InstallAfterFlash/MaxxAudio_CM12_V3.zip
Finding update package...
I:Update location: /sdcardOTAUpdates/InstallAfterFlash/MaxxAudio_CM12_V3.zip
E:unknown volume for path

**Comment by MatthewBooth** [comment]
This is very similar to #33 and should be fixed at the same time. As I mentioned there, I will try to find time tonight to fix these issues.
