### ISSUE TITLE
2.5.3 addons crashes

### ISSUE THREAD

**Issue by XrTV** [MatthewBooth/OTAUpdates#66]
Application takes off when opening addon...
...i made addona itself, I messed up nothing.

**Comment by XrTV** [comment]
12-26 01:47:57.693  1578  1660 I ActivityManager: START u0 {cmp=com.ota.updates/.activities.AddonActivity} from uid 1000 on display 0
12-26 01:47:57.923  1578  1724 I ActivityManager: Displayed com.ota.updates/.activities.AddonActivity: +224ms
12-26 01:47:57.935 30170 30206 D OpenGLRenderer: endAllStagingAnimators on 0xb7308260 (RippleDrawable) with handle 0xb73e9198
12-26 01:47:58.271 30170 30170 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-26 01:47:58.272 30170 30170 E AndroidRuntime: FATAL EXCEPTION: main
12-26 01:47:58.272 30170 30170 E AndroidRuntime: Process: com.ota.updates, PID: 30170
12-26 01:47:58.272 30170 30170 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1044)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at java.text.DateFormat.parse(DateFormat.java:577)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at com.ota.updates.activities.AddonActivity$AddonsArrayAdapter.getView(AddonActivity.java:286)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.AbsListView.obtainView(AbsListView.java:2374)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.ListView.measureHeightOfChildren(ListView.java:1281)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.ListView.onMeasure(ListView.java:1188)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.View.measure(View.java:18819)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.View.measure(View.java:18819)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.View.measure(View.java:18819)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.View.measure(View.java:18819)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.View.measure(View.java:18819)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6025)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:606)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5424)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-26 01:47:58.272 30170 30170 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-26 01:47:58.275  1578  1862 W ActivityManager:   Force finishing activity com.ota.updates/.activities.AddonActivity
12-26 01:47:58.280  1578  1862 W ActivityManager:   Force finishing activity com.ota.updates/.activities.MainActivity
12-26 01:47:58.330  1578  1805 I OpenGLRenderer: Initialized EGL, version 1.4
12-26 01:47:58.780  1578  1677 W ActivityManager: Activity pause timeout for ActivityRecord{d984e2c u0 com.ota.updates/.activities.AddonActivity t833 f}
12-26 01:48:08.289  1578  1677 W ActivityManager: Activity destroy timeout for ActivityRecord{143f9cc u0 com.ota.updates/.activities.MainActivity t833 f}

**Comment by lucadalba** [comment]
+1
I have the same problem

**Comment by sunsettrack4** [comment]
@Mr-MEX @lucadalba There's an "updated-at" string in your addons.xml. Please change it to "published-at" to fix that issue. Reference: https://github.com/MatthewBooth/OTAUpdates/commit/e6ad5af80dd06de5523010ea5e4ddb251d8db6fb
